//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DnevniIzvjestaj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DnevniIzvjestaj()
        {
            this.Recepcija = new HashSet<Recepcija>();
        }
    
        public int DnevniIzvjestajID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public int RezervacijaID { get; set; }
        public int RecepcionerID { get; set; }
    
        public virtual Rezervacija Rezervacija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepcija> Recepcija { get; set; }
        public virtual Recepcioner Recepcioner { get; set; }
    }
}
