//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelEntities : DbContext
    {
        public HotelEntities()
            : base("name=HotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckIn> CheckIn { get; set; }
        public virtual DbSet<CheckOut> CheckOut { get; set; }
        public virtual DbSet<DnevniIzvjestaj> DnevniIzvjestaj { get; set; }
        public virtual DbSet<Gost> Gost { get; set; }
        public virtual DbSet<HotelT> HotelT { get; set; }
        public virtual DbSet<LokacijaSobe> LokacijaSobe { get; set; }
        public virtual DbSet<Recepcija> Recepcija { get; set; }
        public virtual DbSet<Rezervacija> Rezervacija { get; set; }
        public virtual DbSet<Soba> Soba { get; set; }
        public virtual DbSet<Zaduzenja> Zaduzenja { get; set; }
        public virtual DbSet<Recepcioner> Recepcioner { get; set; }
        public virtual DbSet<Kontakt> Kontakt { get; set; }
        public virtual DbSet<Slika> Slika { get; set; }
    }
}
