//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recepcija()
        {
            this.HotelT = new HashSet<HotelT>();
        }
    
        public int RecepcijaID { get; set; }
        public int DnevniIzvjestajID { get; set; }
        public Nullable<int> BrojRezervacija { get; set; }
        public Nullable<double> UkupnaZarada { get; set; }
    
        public virtual DnevniIzvjestaj DnevniIzvjestaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelT> HotelT { get; set; }
    }
}
