//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacija()
        {
            this.DnevniIzvjestaj = new HashSet<DnevniIzvjestaj>();
        }
    
        public int RezervacijaID { get; set; }
        public int GostID { get; set; }
        public int SobaID { get; set; }
        public int CheckInID { get; set; }
        public int CheckOutID { get; set; }
        public string BrojOdraslih { get; set; }
        public string BrojDjece { get; set; }
        public string TipPonude { get; set; }
        public string DodatneInformacije { get; set; }
    
        public virtual CheckIn CheckIn { get; set; }
        public virtual CheckOut CheckOut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DnevniIzvjestaj> DnevniIzvjestaj { get; set; }
        public virtual Gost Gost { get; set; }
        public virtual Soba Soba { get; set; }
    }
}
