//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Slika
    {
        public int SlikaID { get; set; }
        [Required]
        public string Opis { get; set; }
        public string SlikaStaza { get; set; }
        public string ThumbStaza { get; set; }
        public Nullable<System.DateTime> DatumKreiranja { get; set; }
    }
}
