//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorisnikRole
    {
        public int KorisnikRoleID { get; set; }
        public int KorisnikID { get; set; }
        public int RoleVrsteID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual RoleVrste RoleVrste { get; set; }
    }
}
