//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleVrste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoleVrste()
        {
            this.KorisnikRole = new HashSet<KorisnikRole>();
        }
    
        public int RoleVrsteID { get; set; }
        public string RoleIme { get; set; }
        public string RoleOpis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KorisnikRole> KorisnikRole { get; set; }
    }
}
